resolver: lts-14.4
packages:
  - asterius
  - binaryen
  - ghc-toolkit
  - inline-js/inline-js-core
  - npm-utils
  - wabt
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.6.5:
        url: https://6575-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        sha256: a0ebc4ef111fe4d12a24448e01abedc4975d339d685c4cb572cef6f055762f2d
    linux64-custom-asterius:
      8.6.5:
        url: https://6577-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        sha256: 10d9bf87cf876ad8ea360dbe0071fa32cf60dded9d6695cda91c418cefc8256f
    linux64-custom-asterius-musl:
      8.6.5:
        url: https://6576-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-alpine-linux.tar.xz
        sha256: 862f92489691607edf319102b7c533dd6b18d84929fa0551a05e5336966f9f1d
    macosx-custom-asterius:
      8.6.5:
        url: https://6578-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-apple-darwin.tar.xz
        sha256: d743e30ded14b02a4e0cb123a94f663b8096b34af5f4d82ed4a13924718344f9
