resolver: lts-14.7
packages:
  - asterius
  - binaryen
  - ghc-toolkit
  - inline-js/inline-js-core
  - npm-utils
  - wabt
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.6.5:
        url: https://6823-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        sha256: faa780dd143058b17ba4856708219440488ac0209b056ebfd2ff2c2134c34f82
    linux64-custom-asterius:
      8.6.5:
        url: https://6827-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        sha256: 69d4a536e61ea05d4cfa1c92d43a9a0af066fb5f500889bd9f42b370114fa3c5
    linux64-custom-asterius-musl:
      8.6.5:
        url: https://6825-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-alpine-linux.tar.xz
        sha256: 5eb622b5209f6e5db4c87c35c32b52e77ccfcc49b7955f167d441028d53f9f94
    macosx-custom-asterius:
      8.6.5:
        url: https://6826-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-apple-darwin.tar.xz
        sha256: 64246ab4e6435843c7f71a4ee00647823f2d898d9cb726f657645c7b0c7a7ad6
