resolver: nightly-2020-01-25
extra-deps:
  - https://github.com/tweag/binaryen/archive/ddf4c811e809e49aa852d59746f5e33a5a2ceb24.tar.gz
  - url: https://github.com/tweag/inline-js/archive/bd000373e0f02d213a881119298e1aea5962e149.tar.gz
    subdirs:
      - inline-js-core
  - https://github.com/tweag/wabt/archive/8da96d3bb3e4729412410a71180a077cab116ee9.tar.gz
packages:
  - asterius
  - ghc-toolkit
  - npm-utils
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.8.2:
        url: https://9634-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.2-x86_64-unknown-linux.tar.xz
        content-length: 120875724
        sha256: ccd027fb51a70a03c2da329dac0cfca22a886359c3491640f49beb7dad54e48a
    linux64-custom-asterius:
      8.8.2:
        url: https://9635-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.2-x86_64-unknown-linux.tar.xz
        content-length: 118550552
        sha256: 295f203893b62e8ac07d3fbd91d8cec20ca010e98ccc4a59d351035458bb742e
    linux64-custom-asterius-musl:
      8.8.2:
        url: https://9632-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.2-x86_64-alpine-linux.tar.xz
        content-length: 134025832
        sha256: 6cfbd3aa142c16f2401a8f621c869bc5bffc90d281975d5bc0637ee7c3403509
    macosx-custom-asterius:
      8.8.2:
        url: https://9630-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.2-x86_64-apple-darwin.tar.xz
        content-length: 124903432
        sha256: 7772becb4b87e1e6a98b823821d28e8fa56c9113e9cf118ffdb2dc705cb7940f
