resolver: lts-15.10
extra-deps:
  - https://github.com/tweag/haskell-binaryen/archive/6e782a0a42df344afa6c8d5e391160bd172348d8.tar.gz
  - url: https://github.com/tweag/inline-js/archive/114848a9f750b5e9c2f8ca056cc29d84bbab0bae.tar.gz
    subdirs:
      - inline-js-core
packages:
  - asterius
  - ghc-toolkit
  - npm-utils
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius-tinfo6.tar.xz
        content-length: 150979392
        sha256: ea059b833a9eb046bb4f9c4dfa948dedd5a10bf8568f0b82dabd07543f42c704
    linux64-custom-asterius:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius.tar.xz
        content-length: 148216692
        sha256: a1999eca714f046809af1cf1f7b90a16507e6fe3284ca30dfcb749e53bad9ee2
    linux64-custom-asterius-musl:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-linux64-custom-asterius-musl.tar.xz
        content-length: 165434816
        sha256: 791520646f2f4536427ac6c9ecfa6da2aa6bfee09085cb6f60b8cb6990b12857
    macosx-custom-asterius:
      8.8.3:
        url: https://asterius.s3-us-west-2.amazonaws.com/ghc-8.8.3-macosx-custom-asterius.tar.xz
        content-length: 158959324
        sha256: d8fb9e7086f72a06dcc61ef8da0a3630528516dafe77ecacd44262707347014e
