resolver: lts-15.2
extra-deps:
  - https://github.com/tweag/binaryen/archive/00cc255cd1015bb5ab3fb4bf145a57fe5230f3d1.tar.gz
  - url: https://github.com/tweag/inline-js/archive/bd000373e0f02d213a881119298e1aea5962e149.tar.gz
    subdirs:
      - inline-js-core
  - https://github.com/tweag/wabt/archive/29c85806e3fce79d95a0fa5ca22757eb2d1c75c9.tar.gz
packages:
  - asterius
  - ghc-toolkit
  - npm-utils
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.8.2:
        url: https://9647-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.2-x86_64-unknown-linux.tar.xz
        content-length: 138292836
        sha256: 4086d16c38ecf00e6e86bd02e8b6e1ff8466b98ec58c749b4d95c6ee59aac8c8
    linux64-custom-asterius:
      8.8.2:
        url: https://9641-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.2-x86_64-unknown-linux.tar.xz
        content-length: 136117152
        sha256: e271813f61ab502ebcb5208a89421df3bd67ce6c45b65ab06e017c6383c629db
    linux64-custom-asterius-musl:
      8.8.2:
        url: https://9644-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.2-x86_64-alpine-linux.tar.xz
        content-length: 152176192
        sha256: d77e5f609a74eed611a68a9204e1c4c3eb075754e11a106f9f3eaafe47745da5
    macosx-custom-asterius:
      8.8.2:
        url: https://9642-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.2-x86_64-apple-darwin.tar.xz
        content-length: 145151480
        sha256: d294083bbe29d21da52b53666bfcf182136f3536fdf23fab23fd6a5f174d02c9
