resolver: lts-14.16
packages:
  - asterius
  - binaryen
  - ghc-toolkit
  - inline-js/inline-js-core
  - npm-utils
  - wabt
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.6.5:
        url: https://8136-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        sha256: bb8bbb3dc0fce4fa5c0c141d2eda780df61d3ee1f0ad37ceb9ad4ec0ee701b2c
    linux64-custom-asterius:
      8.6.5:
        url: https://8134-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-unknown-linux.tar.xz
        sha256: a91a7a481865a3a23af3b8eabd97d839427348cfbfbeb7f9f8e68af821c06614
    linux64-custom-asterius-musl:
      8.6.5:
        url: https://8135-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-alpine-linux.tar.xz
        sha256: 2718f8a539188268a091d86676d400ec77b5b1fa925ea654187d50f0854082b2
    macosx-custom-asterius:
      8.6.5:
        url: https://8137-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.6.5-x86_64-apple-darwin.tar.xz
        sha256: f7c5784fd81374565bd23014c503eeca7199f8eb388c2f95186eae75d22aca0a
