resolver: lts-16.13
compiler: ghc-8.8.4
extra-deps:
  - binaryen-0.0.3.0
  - url: https://github.com/tweag/inline-js/archive/bd488387d4f3d89e1d21daa3685cad9b2154cde8.tar.gz
    subdirs:
      - inline-js-core
packages:
  - asterius
  - ghc-toolkit
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.8.4:
        url: https://github.com/TerrorJack/ghc/releases/download/ghc-8.8.4-200908/ghc-8.8.4-linux64-hadrian-tinfo6-200908.tar.xz
        content-length: 68565952
        sha256: 36dc78ba0358aec788608f00a3b390d21f3b963f1fa8cf12fbbaa01aecc7b525
    linux64-custom-asterius:
      8.8.4:
        url: https://github.com/TerrorJack/ghc/releases/download/ghc-8.8.4-200908/ghc-8.8.4-linux64-hadrian-standard-200908.tar.xz
        content-length: 68559484
        sha256: b2f1609912f58b44f43ecf8f4e50eb25bd9a8ab9345a1cf2d1438eeeda5bf50b
    linux64-custom-asterius-musl:
      8.8.4:
        url: https://github.com/TerrorJack/ghc/releases/download/ghc-8.8.4-200908/ghc-8.8.4-linux64-musl-200908.tar.xz
        content-length: 169372216
        sha256: 432d4a65c33961ef74ee8bd63ab9121cdbb75b0d23e3a7b63d8933228ee111f1
    macosx-custom-asterius:
      8.8.4:
        url: https://github.com/TerrorJack/ghc/releases/download/ghc-8.8.4-200908/ghc-8.8.4-macosx-hadrian-200908.tar.xz
        content-length: 93241708
        sha256: a713f0b5a9f931a69219881c93a464b7199c59c5368a42c16fcf7347fe0f1b2b
    windows64-custom-asterius:
      8.8.4:
        url: https://github.com/TerrorJack/ghc/releases/download/ghc-8.8.4-200908/ghc-8.8.4-windows64-200908.tar.xz
        content-length: 186533012
        sha256: 3c0fa1b2901b49ee12fddb911fd1ba8f78f567972cb3fe16b1a862ec72ac633e
