resolver: lts-16.27
extra-deps:
  - binaryen-0.0.5.0
  - url: https://github.com/tweag/inline-js/archive/ef675745e84d23d51c50660d40acf9e684fbb2d6.tar.gz
    subdirs:
      - inline-js-core
flags:
  binaryen:
    system-binaryen: true
  ghc-asterius:
    integer-gmp: true
ghc-options:
  $everything: -j
packages:
  - asterius
  - ghc-toolkit
  - lib/ghc-asterius
  - lib/ghc-boot-asterius
  - lib/ghc-boot-th-asterius
  - lib/ghc-heap-asterius
  - lib/ghci-asterius
  - lib/template-haskell-asterius
  - wasm-toolkit
