resolver: lts-15.8
extra-deps:
  - https://github.com/tweag/haskell-binaryen/archive/00d2bfc92c52dd7410b9fded560f033c078a2d33.tar.gz
  - url: https://github.com/tweag/inline-js/archive/114848a9f750b5e9c2f8ca056cc29d84bbab0bae.tar.gz
    subdirs:
      - inline-js-core
  - https://github.com/tweag/wabt/archive/96705e56fe0018c59270f8685f682fb3605d66f4.tar.gz
packages:
  - asterius
  - ghc-toolkit
  - npm-utils
  - wasm-toolkit


ghc-variant: asterius

setup-info:
  ghc:
    linux64-custom-asterius-tinfo6:
      8.8.3:
        url: https://13211-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.3-x86_64-unknown-linux.tar.xz
        content-length: 146042364
        sha256: 85f3362d93b02bd49ca4c33dd72a9928faaeee43fbfbdbe3a9d2c81f2bf89e02
    linux64-custom-asterius:
      8.8.3:
        url: https://13210-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.3-x86_64-unknown-linux.tar.xz
        content-length: 143629148
        sha256: 376e2e802f5a6f13a4f2b1da0cad08c615d228ac9046bb4f41a165b2324425d3
    linux64-custom-asterius-musl:
      8.8.3:
        url: https://13209-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.3-x86_64-alpine-linux.tar.xz
        content-length: 160135168
        sha256: 5a920339d4fc7e0372194db81f77b89a291d012d28ec220dd7d37dd62728dad9
    macosx-custom-asterius:
      8.8.3:
        url: https://13208-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.8.3-x86_64-apple-darwin.tar.xz
        content-length: 161347076
        sha256: b842f3f45b461b77239cf4a5ba7a80aac6ceaeed8951460aa4c6626e62e518ee
