version: 2.1

jobs:

  asterius-build-docs:
    docker:
      - image: terrorjack/asterius:dev
    steps:
      - run:
          name: Ensure we are on `tweag/asterius`
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi
      - run:
          name: Install dependencies
          command: |
            npm install -g netlify-cli
      - checkout
      - run:
          name: Build & push docs
          command: |
            cd docs
            sphinx-build . _build
            pushd _build
            curl -L https://raw.githubusercontent.com/tweag/asterius/examples/ormolu.tar.xz | tar xJ
            curl -L https://raw.githubusercontent.com/tweag/asterius/examples/pandoc.tar.xz | tar xJ
            popd
            if [ $CIRCLE_BRANCH = "master" ]
            then
              netlify deploy --dir=_build --message="$CIRCLE_SHA1" --prod
            else
              netlify deploy --dir=_build --message="$CIRCLE_SHA1"
            fi

workflows:
  version: 2
  build:
    jobs:
      - asterius-build-docs
