name: binaryen
version: 0.0.1
category: Compiler
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/asterius

extra-source-files:
  - binaryen/**/**
  - cbits/**/**
  - CHANGELOG.md
  - LICENSE
  - README.md

custom-setup:
  dependencies:
    - base
    - Cabal
    - directory
    - filepath
    # we need ghc technically only on macOS
    # to work around the lack of MRI scripts
    # via -M support of the `ar` that's
    # shipped with macOS.  We here rely in
    # GHC's built in Ar.
    - ghc

ghc-options: -Wall

dependencies:
  - base

library:
  source-dirs: src

tests:
  binaryen-test:
    source-dirs: test
    main: binaryen-test.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - binaryen
