name: asterius
version: 0.0.1
category: Compiler
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/asterius

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - test/array/**/*.hs
  - test/fib/**/*.hs
  - test/jsffi/**/*.hs
  - test/jsffi/jsffi.mjs
  - test/node-compile/node-compile.js
  - test/rtsapi/**/*.hs
  - test/rtsapi/rtsapi.mjs
  - test/stableptr/**/*.hs
  - test/todomvc/**/*.hs
  - test/todomvc/**/*.html
  - test/teletype/**/*.hs
  - test/teletype/teletype.mjs
  - test/bytearray/**/*.hs
  - test/bigint/**/*.hs
  - test/bigint/bigint.mjs
  - test/vault/**/*.hs
  - test/vault/vault.mjs
  - test/cloudflare/**/*.hs
  - test/cloudflare/cloudflare.mjs

data-files:
  - rts/*.mjs
  - boot-init.sh
  - boot.sh

custom-setup:
  dependencies:
    - base
    - Cabal
    - ghc-toolkit

ghc-options: -Wall

dependencies:
  - base
  - binary
  - binaryen
  - bytestring
  - Cabal
  - containers
  - deepseq
  - directory
  - filepath
  - ghc
  - ghc-prim
  - ghc-toolkit
  - inline-js
  - mtl
  - npm-utils
  - optparse-applicative
  - parsec
  - process
  - transformers
  - wasm-toolkit

library:
  source-dirs: src
  other-modules: Paths_asterius
  other-extensions:
    - DeriveGeneric
    - DeriveDataTypeable
    - FlexibleContexts
    - GADTs
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MagicHash
    - NamedFieldPuns
    - OverloadedLists
    - OverloadedStrings
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - StrictData
    - TemplateHaskell
    - TypeFamilies
    - UnboxedTuples

executables:
  ahc:
    source-dirs: app
    main: ahc.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  ahc-pkg:
    source-dirs: app
    main: ahc-pkg.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  ahc-boot:
    source-dirs: app
    main: ahc-boot.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  ahc-link:
    source-dirs: app
    main: ahc-link.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  ahc-ar:
    source-dirs: app
    main: ahc-ar.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  ahc-ld:
    source-dirs: app
    main: ahc-ld.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

tests:
  nir-test:
    source-dirs: test
    main: nir-test.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius
    other-extensions:
      - OverloadedLists
      - OverloadedStrings

  fib:
    source-dirs: test
    main: fib.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  jsffi:
    source-dirs: test
    main: jsffi.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  array:
    source-dirs: test
    main: array.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  stableptr:
    source-dirs: test
    main: stableptr.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  rtsapi:
    source-dirs: test
    main: rtsapi.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  todomvc:
    source-dirs: test
    main: todomvc.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  node-compile:
    source-dirs: test
    main: node-compile.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius
      - QuickCheck

  teletype:
    source-dirs: test
    main: teletype.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  bytearray:
    source-dirs: test
    main: bytearray.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  bigint:
    source-dirs: test
    main: bigint.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  vault:
    source-dirs: test
    main: vault.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius

  cloudflare:
    source-dirs: test
    main: cloudflare.hs
    ghc-options: -threaded -feager-blackholing -rtsopts
    dependencies:
      - asterius
