name: build

on:
  - push
  - pull_request

jobs:

  build:
    name: build
    runs-on: ubuntu-18.04
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: boot
        run: |
          podman container run \
            --network host \
            --pull always \
            --volume $(pwd):/workspaces/asterius \
            --workdir /workspaces/asterius \
            terrorjack/asterius:dev-200517 \
            .github/workflows/boot.sh
