name: build

on:
  - push
  - pull_request

jobs:

  build:
    name: build
    runs-on: ubuntu-18.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          stack-version: 2.3.1
          enable-stack: true
          stack-no-global: true

      - name: setup-node-14
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 14.3.0

      - name: setup-deps
        run: |
          sudo apt install -y \
            libnuma-dev
          curl http://http.us.debian.org/debian/pool/main/b/binaryen/binaryen_93-1_amd64.deb -o /tmp/binaryen.deb
          sudo dpkg -i /tmp/binaryen.deb

      - name: checkout
        uses: actions/checkout@v2

      - name: boot
        run: |
          stack update
          stack -j2 build --test --no-run-tests asterius
          . .envrc
          ahc-boot
