name: build

on:
  - push
  - pull_request

jobs:

  boot:
    name: boot
    runs-on: ubuntu-18.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          cabal-version: 3.2.0.0
          stack-version: 2.3.1
          enable-stack: true

      - name: setup-node-14
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 14.3.0

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-deps
        run: |
          .github/workflows/setup-deps.sh

      - name: boot
        run: |
          stack update
          stack -j2 build --test --no-run-tests asterius
          . .envrc
          ahc-boot

      - name: upload-cache
        uses: actions/cache@v2
        with:
          key: cache-${{ github.sha }}
          path: |
            ~/.stack
            .

  ghc-testsuite:
    name: ghc-testsuite
    needs: boot
    runs-on: ubuntu-18.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          cabal-version: 3.2.0.0
          stack-version: 2.3.1
          enable-stack: true

      - name: setup-node-14
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 14.3.0

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-deps
        run: |
          .github/workflows/setup-deps.sh

      - name: download-cache
        uses: actions/cache@v2
        with:
          key: cache-${{ github.sha }}
          path: |
            ~/.stack
            .

      - name: ghc-testsuite
        run: |
          GHCRTS=-N2 stack test asterius:ghc-testsuite --test-arguments="-j2 --timeout=300s" || true

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-report.csv
          path: asterius/test-report.csv
